version: '2'
services:
    php:
        build: ./php.dockerfile
        volumes:
            - ./www:/var/www/html
    nginx:
        build: ./nginx.dockerfile
        volumes:
            - ./www:/var/www/html
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        port:
            - "8888:80"
